### ISSUE TITLE
[ feature request ] Add color to theme

### ISSUE THREAD

**Issue by yonas** [ikebastuz/wiper#27]
It would be nice to have a color theme like [gdu](https://github.com/dundee/gdu).

**Comment by ikebastuz** [comment]
Hello, @yonas!

Thank you for your request.

However, I prefer to keep the UI as simple as possible. Even the colored "gradient" bars are turned off by default because, for many people, they are just visual noise.

<img width="864" alt="Screenshot 2024-05-26 at 05 45 37" src="https://github.com/ikebastuz/wiper/assets/24222413/69e9edde-9a84-4e54-8b09-8f47afcabcef">
<img width="857" alt="Screenshot 2024-05-26 at 05 45 26" src="https://github.com/ikebastuz/wiper/assets/24222413/3bdea279-3bbf-430f-b24e-fd4ed51bf75a">
